# Generated by Django 3.0.5 on 2020-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FairTradeBorrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('pan', models.CharField(max_length=32)),
                ('education', models.TextField()),
                ('cur_emp_years', models.IntegerField()),
                ('cur_adr_years', models.IntegerField()),
                ('DtoI', models.FloatField()),
                ('credit_debt', models.FloatField()),
            ],
            options={
                'ordering': ['username', 'password', 'first_name', 'last_name', 'dob', 'pan', 'education', 'cur_emp_years', 'cur_adr_years'],
            },
        ),
    ]
