# Generated by Django 3.0.5 on 2020-05-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrower', '0002_auto_20200504_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fairtradeborrower',
            old_name='DtoI',
            new_name='d_to_i',
        ),
        migrations.RemoveField(
            model_name='fairtradeborrower',
            name='id',
        ),
        migrations.AddField(
            model_name='fairtradeborrower',
            name='income',
            field=models.FloatField(default=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fairtradeborrower',
            name='username',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
