# Generated by Django 3.0.5 on 2020-05-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fairtradelender',
            options={},
        ),
    ]
