# Generated by Django 3.0.5 on 2020-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lender', '0003_auto_20200505_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairtradelender',
            name='account_type',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
